// USERS
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const GET_USERS = 'GET_USERS';

// PRODUCTS
export const GET_PRODUCTS_BY_ARRIVAL = 'GET_PRODUCTS_BY_ARRIVAL';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const CLEAR_PRODUCT_DETAIL = 'CLEAR_PRODUCT_DETAIL';


export const GET_BRANDS = 'GET_BRANDS';



// UI
export const OPEN_MODULE = 'OPEN_MODULE';
export const CLOSE_MODULE = 'CLOSE_MODULE';
export const GET_MODULE = 'GET_MODULE';