// USERS
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const GET_USERS = 'GET_USERS';

// PRODUCTS
export const GET_PRODUCTS_BY_ARRIVAL = 'GET_PRODUCTS_BY_ARRIVAL';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const CLEAR_PRODUCT_DETAIL = 'CLEAR_PRODUCT_DETAIL';


export const GET_BRANDS = 'GET_BRANDS';



// UI
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const TOGGLE_ACCOUNT = 'TOGGLE_ACCOUNT';
export const TOGGLE_CART = 'TOGGLE_CART';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const TURN_ALL_FALSE = 'TURN_ALL_FALSE';